os: linux
dist: xenial
language: node_js
node_js: lts/*

script:
  - npm run quality:check
  - NODE_ENV=production npm run build
deploy:
  - provider: pages
    on:
      branch: main
      repo: taylorgrinn/tygr-auth
    edge: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
  - provider: npm
    on:
      branch: main
      tags: true
      repo: taylorgrinn/tygr-auth
    edge: true
    email: grinntaylor+old@gmail.com
    api_token: $NPM_TOKEN
